---
channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.11
  - pytorch::pytorch>=2.9
  - pytorch::pytorch-cuda=12.9
  - pytest
  - pytest-mock
  - click
  - pandas
  - pip:
    - pyro-ppl>=1.9
